### PR TITLE
Upgrade to Next 13

### PR DESCRIPTION
**Pull request by soupaJ**
Upgrading to Next 13 to take advantage of some of the latest features like `app` router. This PR does not attempt to migrate to the `app` router just yet.

### CODE REVIEW

**Comment by soupaJ** [comment]
@jkulton The minimum node version was bumped to node v16 for Next.js 13 so I had to bump the versions in the github workflow.

https://nextjs.org/docs/pages/building-your-application/upgrading/version-13#v13-summary

**Comment by jkulton** [comment]
@soupaJ I also tried to update the project on the Vercel side (and think I did successfully) as it gave me a warning about being on an old version of Node.

I'll test out your changes later this week and see about getting this deployed. 👍

**Comment by jkulton** [comment]
☑️ Upgraded Vercel project to Node v18
☑️ Code looks good
☑️ Staging deployment looks good

🚀 🚀 🚀 

I'm going to bypass the check since it's looking for the v14 check that no longer exists.

**Comment by jkulton** [comment]
New version is live, thanks @soupaJ!

I also updated the [changelog](https://www.gistdoc.com/2ff7302367044178af3eeaee4384a4ba)

**Pull request merged**
